//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimulacionBot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT_Mensajes_Telefonica_DigitalBlue
    {
        public int Id { get; set; }
        public string ServiceNumber { get; set; }
        public string Observaciones { get; set; }
        public string Cliente { get; set; }
        public string Departamento { get; set; }
        public string Ciudad { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public bool Estado { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string EstadoCliente { get; set; }
        public Nullable<int> TipoBase { get; set; }
        public Nullable<int> Particion { get; set; }
    }
}
